Repository unosquare/ffmediaelement, pull requests merged in 2019-03, with the labels that each got.

#329 Better rendering and Timing
  Unosquare.FFME.Common/Commands/CommandManager.Direct.cs
  Unosquare.FFME.Common/Commands/CommandManager.Priority.cs
  Unosquare.FFME.Common/Commands/CommandManager.Seek.cs
  Unosquare.FFME.Common/Commands/CommandManager.cs
  Unosquare.FFME.Common/Decoding/AudioFrame.cs
  Unosquare.FFME.Common/Decoding/MediaComponent.cs
  Unosquare.FFME.Common/Decoding/MediaComponentSet.cs
  Unosquare.FFME.Common/Decoding/MediaContainer.cs
  Unosquare.FFME.Common/Decoding/SubtitleFrame.cs
  Unosquare.FFME.Common/Decoding/VideoFrame.cs
  Unosquare.FFME.Common/Logging.cs
  Unosquare.FFME.Common/MediaEngine.Workers.cs
  Unosquare.FFME.Common/MediaEngine.cs
  Unosquare.FFME.Common/Primitives/MediaBlockBuffer.cs
  Unosquare.FFME.Common/Primitives/ThreadWorkerBase.cs
  Unosquare.FFME.Common/Primitives/WorkerDelayProvider.cs
  Unosquare.FFME.Common/Shared/Constants.cs
  Unosquare.FFME.Common/Shared/Extensions.cs
  Unosquare.FFME.Common/Shared/IMediaEngineState.cs
  Unosquare.FFME.Common/Shared/MediaBlock.cs
  Unosquare.FFME.Common/Shared/MediaEngineState.cs
  Unosquare.FFME.Common/Shared/MediaOptions.cs
  Unosquare.FFME.Common/Workers/BlockRenderingWorker.cs
  Unosquare.FFME.Common/Workers/FrameDecodingWorker.cs
  Unosquare.FFME.Common/Workers/PacketReadingWorker.cs
  Unosquare.FFME.Windows.Sample/App.xaml.cs
  Unosquare.FFME.Windows.Sample/Controls/ControllerPanelControl.xaml
  Unosquare.FFME.Windows.Sample/Controls/PropertiesPanelControl.xaml
  Unosquare.FFME.Windows.Sample/MainWindow.MediaEvents.cs
  Unosquare.FFME.Windows.Sample/ViewModels/PlaylistViewModel.cs
  Unosquare.FFME.Windows/MediaElement.DependencyProperties.cs
  Unosquare.FFME.Windows/MediaElement.MediaProperties.cs
  Unosquare.FFME.Windows/MediaElement.RenderEvents.cs
  Unosquare.FFME.Windows/Platform/GuiTimer.cs
  Unosquare.FFME.Windows/Rendering/AudioRenderer.cs
Labels: bug, enhancement

#334 Independent clocks implementation
  Unosquare.FFME.Common/Aspects.cs
  Unosquare.FFME.Common/Commands/CommandManager.Direct.cs
  Unosquare.FFME.Common/Commands/CommandManager.Priority.cs
  Unosquare.FFME.Common/Commands/CommandManager.Seek.cs
  Unosquare.FFME.Common/Decoding/MediaComponentSet.cs
  Unosquare.FFME.Common/Decoding/MediaContainer.cs
  Unosquare.FFME.Common/MediaEngine.Workers.cs
  Unosquare.FFME.Common/MediaEngine.cs
  Unosquare.FFME.Common/Shared/Constants.cs
  Unosquare.FFME.Common/Shared/Extensions.cs
  Unosquare.FFME.Common/Shared/MediaEngineState.cs
  Unosquare.FFME.Common/Shared/MediaOptions.cs
  Unosquare.FFME.Common/Workers/BlockRenderingWorker.cs
  Unosquare.FFME.Common/Workers/FrameDecodingWorker.cs
  Unosquare.FFME.Common/Workers/TimingController.cs
  Unosquare.FFME.Windows.Sample/App.xaml.cs
  Unosquare.FFME.Windows.Sample/MainWindow.MediaEvents.cs
  Unosquare.FFME.Windows.Sample/MainWindow.MediaRendering.cs
  Unosquare.FFME.Windows/Events/RenderingAudioEventArgs.cs
  Unosquare.FFME.Windows/MediaElement.RenderEvents.cs
  Unosquare.FFME.Windows/Rendering/AudioRenderer.cs
  Unosquare.FFME.Windows/Rendering/RendererOptions.cs
  Unosquare.FFME.Windows/Rendering/VideoRenderer.cs
  Unosquare.FFME.Windows/Rendering/Wave/WaveFormat.cs
Labels: enhancement

#340 In netcoreapp3.0 the CopyMemory native function does not exist, use RtlCopyMemory
  Unosquare.FFME.Windows/Platform/WindowsNativeMethods.cs
Labels: bug

#348 Issue #248 Implementing recording capabilities
  Unosquare.FFME.Common/Commands/CommandManager.Seek.cs
  Unosquare.FFME.Common/Core/FFDictionary.cs
  Unosquare.FFME.Common/Core/FFDictionaryEntry.cs
  Unosquare.FFME.Common/Core/FFInterop.cs
  Unosquare.FFME.Common/Decoding/MediaComponent.cs
  Unosquare.FFME.Common/Decoding/MediaContainer.cs
  Unosquare.FFME.Common/Decoding/SubtitleFrame.cs
  Unosquare.FFME.Common/Engine/Extensions.cs
  Unosquare.FFME.Common/Engine/IMediaConnector.cs
  Unosquare.FFME.Common/Engine/MediaEngineState.cs
  Unosquare.FFME.Common/Engine/MediaInfo.cs
  Unosquare.FFME.Common/Engine/OptionMeta.cs
  Unosquare.FFME.Common/MediaEngine.Static.cs
  Unosquare.FFME.Common/Workers/BlockRenderingWorker.cs
  Unosquare.FFME.Common/Workers/FrameDecodingWorker.cs
  Unosquare.FFME.Common/Workers/PacketReadingWorker.cs
  Unosquare.FFME.Windows.Sample/App.xaml.cs
  Unosquare.FFME.Windows.Sample/Foundation/TransportStreamRecorder.cs
  Unosquare.FFME.Windows.Sample/MainWindow.MediaEvents.cs
  Unosquare.FFME.Windows.Sample/MainWindow.xaml.cs
  Unosquare.FFME.Windows/Events/FrameDecodedEventArgs.cs
  Unosquare.FFME.Windows/Events/InputFormatEventArgs.cs
  Unosquare.FFME.Windows/Events/PacketReadEventArgs.cs
  Unosquare.FFME.Windows/Events/SubtitleDecodedEventArgs.cs
  Unosquare.FFME.Windows/MediaElement.RoutedEvents.cs
  Unosquare.FFME.Windows/MediaElement.cs
  Unosquare.FFME.Windows/Platform/WindowsMediaConnector.cs
Labels: enhancement
